name: Google Cloud Function Deployment
on:
  push:
    branches:
      - main
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GCP Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          name: 'gocroot'
          runtime: 'go122'
          entry_point: 'WebHook'
          region: 'asia-southeast1'
          env_vars: 'MONGOSTRING=${{ secrets.MONGOSTRING }},WAQRKEYWORD=${{ secrets.WAQRKEYWORD }},WEBHOOKURL=${{ secrets.WEBHOOKURL }},WEBHOOKSECRET=${{ secrets.WEBHOOKSECRET }},WAPHONENUMBER=${{ secrets.WAPHONENUMBER }}'
      - id: 'test'
        run: |
          'curl "${{ steps.deploy.outputs.url }}"'
          'echo "${{ steps.deploy.outputs.id }}"'
          'echo "${{ steps.deploy.outputs.status }}"'
          'echo "${{ steps.deploy.outputs.version }}"'
          'echo "${{ steps.deploy.outputs.runtime }}"'